## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1

# Uncomment if you're using OpenCV 3
OPENCV_VERSION := 3

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda-9.0

# CUDA architecture setting: going with all of them.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# BLAS choice:
BLAS := open
BLAS_INCLUDE := /home/roger/Workspace/github/CaffeFramework/include
BLAS_LIB := /home/roger/Workspace/github/CaffeFramework/lib

# NOTE: this is required only if you will compile the python interface.
# We need to be able to find Python.h and numpy/arrayobject.h.
PYTHON_LIBRARIES := boost_python3 python3.6m
ANACONDA_HOME := /opt/anaconda/envs/caffe-env
PYTHON_INCLUDE := $(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
                  $(python3 -c "import numpy; print(numpy.get_include())")
PYTHON_LIB := $(python3 -c "from distutils.sysconfig import get_config_var;from os.path import dirname,join ; print(join(dirname(get_config_var('LIBPC')),get_config_var('LDLIBRARY')))")

# Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) #/usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/cuda-9.0/targets/x86_64-linux/lib #/usr/local/lib /usr/lib

# Uncomment to support layers written in Python (will link against Python libs)
WITH_PYTHON_LAYER := 1

# Custom libraries
QC_CUSTOM_INCLUDE := /home/roger/Workspace/github/CaffeFramework/include                              
QC_CUSTOM_LIB := /home/roger/Workspace/github/CaffeFramework/lib   

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @
